# Generated by Django 5.1.7 on 2025-03-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='unidad_medida',
        ),
    ]
