# Generated by Django 5.2 on 2025-05-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_remove_recurso_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Recurso'),
        ),
    ]
