# Generated by Django 5.2 on 2025-05-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_alter_recurso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID del Recurso'),
        ),
    ]
