# Generated by Django 5.2 on 2025-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('rol', models.CharField(editable=False, max_length=50)),
            ],
        ),
    ]
