# Generated by Django 5.2 on 2025-05-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_correo_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='password', max_length=100, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
