# Generated by Django 5.2 on 2025-05-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=1, verbose_name='Cantidad Solicitada')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Esperada')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('devuelta', 'Devuelta')], default='pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de la Solicitud')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.recurso', verbose_name='Recurso Solicitado')),
            ],
            options={
                'verbose_name': 'Solicitud de Recurso',
                'verbose_name_plural': 'Solicitudes de Recursos',
            },
        ),
    ]
